version: '3.4'

services:
  coingardenworld.landingpage:
    image: ${DOCKER_REGISTRY-}coingardenworld.landingpage
    build:
      target: final
      context: .
      dockerfile: landing-page/CoinGardenWorld.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5001:80

  coingardenworld.grpc:
    image: ${DOCKER_REGISTRY-}coingardenworld.landingpage_grpc
    build:
      context: .
      dockerfile: back-end/CoinGardenWorld.LandingPage.Grpc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 7166:80
      - 7167:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
