name: Release Distribution Packages

on:
  repository_dispatch:
    types: [build_success]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "release"
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Mobile Artifacts
    steps:
    
      - name: Get version
        id: get_version
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "::set-output name=VERSION::$VERSION"

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
          # Required, if the artifact is from a different repo
          # Required, if the repo is private a Personal Access Token with `repo` scope is needed
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Optional, workflow file name or ID
          # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
          workflow: build-mobile-apps.yml
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
          # Use the empty string ("") to ignore status or conclusion in the search
          workflow_conclusion: success

      - name: Create Release
        id: create_release
        # Drafts your next Release notes as Pull Requests are merged into "master"
        uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          # config-name: my-config.yml
          # disable-autolabeler: true
          publish: false
          version: ${{ steps.get_version.outputs.VERSION }}
          tag: ${{ steps.get_version.outputs.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      
      - name: Release Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            src/mobile-apps/CoinGardenWorld.Maui/bin/Release/net6.0-android/*Signed.a*
            src/mobile-apps/CoinGardenWorld.Maui/bin/Release/net6.0-windows10.0.19041.0/win10-x64/AppPackages/CoinGardenWorld*/CoinGardenWorld*.msix
            src/mobile-apps/CoinGardenWorld.Maui/bin/Release/net6.0-ios/iossimulator-x64/**/*.app
            src/mobile-apps/CoinGardenWorld.Maui/bin/Release/net6.0-maccatalyst/maccatalyst-x64/publish/*.pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}